FROM astrocrpublic.azurecr.io/runtime:3.2-4
ENV AIRFLOW__LOGGING__BASE_LOG_FOLDER=/usr/local/airflow/logs
ENV AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION=/usr/local/airflow/logs/dag_processor_manager
